/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ps_Inventario;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;
import static ps_Inventario.Dashboard.content;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Antonio
 */
public class Articulos extends javax.swing.JPanel {

    Connect conn;
    Connection reg;
    /**
     * Creates new form Principal
     */
    public Articulos() {
        initComponents();
        conn = new Connect();
        reg = conn.getConnection();
        try {
            GetArticulos();
        } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        bname = new javax.swing.JTextField();
        button = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edit = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        delete = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(238, 238, 238));
        setMinimumSize(new java.awt.Dimension(870, 430));
        setPreferredSize(new java.awt.Dimension(890, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nuevo.setBackground(new java.awt.Color(18, 90, 173));
        nuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nuevoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nuevoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nuevoMousePressed(evt);
            }
        });
        nuevo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nuevo");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        nuevo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 5, 60, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ps_Inventario/images/add-to-database.png"))); // NOI18N
        nuevo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 5, -1, -1));

        add(nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 90, 30));

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("Elemento");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(248, 130, 41));
        jSeparator2.setPreferredSize(new java.awt.Dimension(250, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 580, 20));

        bname.setBackground(new java.awt.Color(238, 238, 238));
        bname.setForeground(new java.awt.Color(102, 102, 102));
        bname.setText("Ingrese el nombre del Elemento a buscar");
        bname.setBorder(null);
        bname.setSelectionColor(new java.awt.Color(248, 130, 41));
        bname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bnameMousePressed(evt);
            }
        });
        bname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnameActionPerformed(evt);
            }
        });
        add(bname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 580, 30));

        button.setBackground(new java.awt.Color(18, 90, 173));
        button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonMousePressed(evt);
            }
        });
        button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(240, 240, 240));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar");
        button.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 5, 60, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ps_Inventario/images/search-database.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        button.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 5, 30, -1));

        add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 100, 30));
        button.getAccessibleContext().setAccessibleDescription("");

        edit.setBackground(new java.awt.Color(5, 115, 0));
        edit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        edit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editMousePressed(evt);
            }
        });
        edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Editar");
        edit.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 5, 60, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ps_Inventario/images/edit-base.png"))); // NOI18N
        edit.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 5, -1, -1));

        add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 90, 30));

        delete.setBackground(new java.awt.Color(153, 9, 0));
        delete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deleteMousePressed(evt);
            }
        });
        delete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Borrar");
        delete.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 5, 60, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ps_Inventario/images/remove-from-database.png"))); // NOI18N
        delete.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 5, -1, -1));

        add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, 90, 30));

        jTable1.setBackground(new java.awt.Color(238, 238, 238));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Elemento", "Fecha", "Categoría", "Descripción", "Stock", "Disponibles"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 850, 300));
    }// </editor-fold>//GEN-END:initComponents

    private void bnameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnameMousePressed
       if(bname.getText().equals("Ingrese el nombre del Elemento a buscar"))
        bname.setText("");
    }//GEN-LAST:event_bnameMousePressed

    private void buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseEntered
        setColorNuevo(button);
    }//GEN-LAST:event_buttonMouseEntered

    private void buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseExited
        resetColorNuevo(button);
    }//GEN-LAST:event_buttonMouseExited

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // Abrir sección
        
        UpElementos p1 = new UpElementos();
        p1.setSize(890, 430);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_jLabel3MousePressed

    private void nuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoMouseEntered
        setColorNuevo(nuevo);
    }//GEN-LAST:event_nuevoMouseEntered

    private void nuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoMouseExited
        resetColorNuevo(nuevo);
    }//GEN-LAST:event_nuevoMouseExited

    private void nuevoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoMousePressed
        // Abrir sección
        UpUsers p1 = new UpUsers();
        p1.setSize(890, 430);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_nuevoMousePressed

    private void editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseEntered
        setColorEditar(edit);
    }//GEN-LAST:event_editMouseEntered

    private void editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseExited
        resetColorEditar(edit);
    }//GEN-LAST:event_editMouseExited

    private void deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseEntered
        setColorEliminar(delete);
    }//GEN-LAST:event_deleteMouseEntered

    private void deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseExited
        resetColorEliminar(delete);
    }//GEN-LAST:event_deleteMouseExited

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        if(bname.getText().equals("") || bname.getText() == null || bname.getText().equals(" "))
            bname.setText("Ingrese el ID del Elemento a buscar");
    }//GEN-LAST:event_jTable1MousePressed
    // BORRAR
    private void deleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMousePressed
        try {
            int idcell = jTable1.getSelectedRow();
            if(idcell <= -1){
                javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar el Elemento a borrar. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                Statement stm = reg.createStatement();
                ResultSet counter = stm.executeQuery("SELECT * FROM `articulos`");

                int count = 0;
                while(counter.next()){count++;}

                String list[][] = new String[count][12];
                int i = 0;
                ResultSet re = stm.executeQuery("SELECT * FROM `articulos`");
                while(re.next()){
                    list[i][0] = re.getString("id");
                    list[i][1] = re.getString("elemento");
                    list[i][2] = re.getString("date");
                    list[i][3] = re.getString("category");
                    list[i][4] = re.getString("description");
                    list[i][5] = re.getString("stock");
                    list[i][6] = re.getString("available");
                    i++;
                }
                String id = list[idcell][0];
                String elem = list[idcell][1];
                if(id == null || id.equals("")){
                    javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar el Elemento a borrar. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                   
                    
                    int I = JOptionPane.showConfirmDialog(this, "Desea Eliminar el Elemento:  \""+elem+"\"");
                    
                    switch (I) {
                        case 0:
                            Statement stm2=null;
                            try {
                                stm2 = reg.createStatement();
                            } catch (SQLException ex) {
                                Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
                            }       try {
                                stm2.executeUpdate("DELETE FROM `articulos` WHERE `id` = '"+id+"'");
                                javax.swing.JOptionPane.showMessageDialog(this, "¡Elemento borrado! \n", "HECHO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                                GetArticulos();
                            } catch (SQLException ex) {
                                Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
                            }       break;
                        case 1:
                            javax.swing.JOptionPane.showMessageDialog(this, "Elemento Restaurado. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                            break;
                        default:
                            break;
                    }
                    
                    
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Users.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteMousePressed

    // EDITAR
    private void editMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMousePressed
        try {
            int idcell = jTable1.getSelectedRow();
            if(idcell <= -1){
                javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar el articulo a editar. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                
                Statement stm = reg.createStatement();
                ResultSet counter = stm.executeQuery("SELECT * FROM `articulos`");

                int count = 0;
                while(counter.next()){count++;}

                String list[][] = new String[count][12];
                int i = 0;
                ResultSet re = stm.executeQuery("SELECT * FROM `articulos`");
                while(re.next()){
                    list[i][0] = re.getString("id");
                    list[i][1] = re.getString("elemento");
                    list[i][2] = re.getString("date");   
                    list[i][3] = re.getString("category");
                    list[i][4] = re.getString("description");
                    list[i][5] = re.getString("stock");
                    list[i][6] = re.getString("available");
                    i++;
                }
                String id = list[idcell][0];
                if(id == null || id.equals("")){
                    javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar el articulo a editar. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    String bid = ""+list[idcell][0];
                    String belemento = list[idcell][1];
                    String bdate = list[idcell][2];
                    String bcategory = list[idcell][3];
                    String bdesc = list[idcell][4];
                    String bstock = list[idcell][5];
                    String bavai = list[idcell][6];            

                    UpElementos p1 = new UpElementos(bid, belemento, bdate, bcategory, bdesc, bstock, bavai);
                    p1.setSize(850, 430);
                    p1.setLocation(0, 0);

                    content.removeAll();
                    content.add(p1, BorderLayout.CENTER);
                    content.revalidate();
                    content.repaint();
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Users.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editMousePressed
    // BUSCAR
    private void buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMousePressed
        try {
            String inf = bname.getText();
            Statement stm = reg.createStatement();
            ResultSet counter = stm.executeQuery("SELECT * FROM `articulos` WHERE elemento LIKE '"+inf+"%'");
            
            int count = 0;
            while(counter.next()){count++;}
            
            String list[][] = new String[count][12];
            int i = 0;
            ResultSet re = stm.executeQuery("SELECT * FROM `articulos` WHERE elemento LIKE '"+inf+"%'");
            while(re.next()){
            list[i][0] = re.getString("id");
            list[i][1] = re.getString("elemento");
            list[i][2] = re.getString("date");
            list[i][3] = re.getString("category");
            list[i][4] = re.getString("description");
            list[i][5] = re.getString("stock");
            list[i][6] = re.getString("available");
            i++;
        }
        
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
        list,
        new String [] {
            "ID", "Elemento","Fecha de Pub.", "Categoría", "Descripción", "Stock", "Disponibles"
        }));
        } catch (SQLException ex) {
            Logger.getLogger(Users.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonMousePressed

    private void bnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnameActionPerformed

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        setColorNuevo(nuevo);
    }//GEN-LAST:event_jLabel3MouseEntered

     private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {                                     
        resetColorNuevo(nuevo);
    }    
     
    void setColorEliminar(JPanel panel){
        panel.setBackground(new Color(191, 11, 0));
    }
    void resetColorEliminar(JPanel panel){
        panel.setBackground(new Color(153, 9, 0));
    }
    
    void setColorEditar(JPanel panel){
        panel.setBackground(new Color(6, 153, 0));
    }
    void resetColorEditar(JPanel panel){
        panel.setBackground(new Color(5, 115, 0));
    }
    
     void setColorNuevo(JPanel panel){
        panel.setBackground(new Color(21, 109, 211));
    }
    void resetColorNuevo(JPanel panel){
        panel.setBackground(new Color(18, 90, 173));
    }
    
    private void GetArticulos() throws SQLException{
        Statement stm = reg.createStatement();
        ResultSet counter = stm.executeQuery("SELECT * FROM `articulos`");
        
        int count = 0;
        while(counter.next()){count++;}
        
        String list[][] = new String[count][12];
        int i = 0;
        ResultSet re = stm.executeQuery("SELECT * FROM `articulos`");
        while(re.next()){
            list[i][0] = re.getString("id");
            list[i][1] = re.getString("elemento");
            list[i][2] = re.getString("date");
            list[i][3] = re.getString("category");
            list[i][4] = re.getString("description");
            list[i][5] = re.getString("stock");
            list[i][6] = re.getString("available");
            i++;
        }
        
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
        list,
        new String [] {
            "ID", "Elemento", "Fecha de Pub.","Categoría", "Descripción", "Stock", "Disponibles"
        }));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JTextField bname;
    private javax.swing.JPanel body;
    private javax.swing.JPanel button;
    private javax.swing.JPanel delete;
    private javax.swing.JPanel edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel nuevo;
    // End of variables declaration//GEN-END:variables
}
