/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ps_Inventario;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 *
 * @author Antonio
 */
public class Principal extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        LocalDate now = LocalDate.now();
        int yearActual = now.getYear();
            
        
        
        año.setText(""+yearActual);  
        
        Calendar fechaFundacion = new GregorianCalendar(1911, 4, 17);
        Calendar ahora = Calendar.getInstance();

        long edadEnDias = (ahora.getTimeInMillis() - fechaFundacion.getTimeInMillis())
                                / 1000 / 60 / 60 / 24;

        int year = Double.valueOf(edadEnDias / 365.25d).intValue();
        int dias = Double.valueOf(edadEnDias % 365.25d).intValue();
        años.setText("Años: "+year+ "\n"+" y \n" +dias+ " Dias ");
    }
    
   
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Text1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Image1 = new javax.swing.JLabel();
        año = new javax.swing.JLabel();
        años = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 238, 238));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("Bienvenido");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Text1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text1.setText("Sistema de Gestión para E.E.T N°1. Control y administracion de");
        add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("forma óptima y fácil el flujo de préstamos y devoluciones de Elementos de gastronomia. ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Esta herramienta le permitirá llevar un control completo y detallado de su Inventario.");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("tendrá acceso a herramientas especiales para tareas específicas, como lo son:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("• Sección de Reportes de acciones en el sistema");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 330, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("• Préstamos");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 170, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("• Devoluciones");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 170, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("• Registro de Usuarios y Elementos Nuevos");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 320, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("• Edición de Usuarios y Elementos existentes");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 330, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("• Eliminar todo tipo de Registros");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 330, -1));

        Image1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ps_Inventario/images/escudo2.png"))); // NOI18N
        add(Image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, -1, -1));

        año.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        año.setForeground(new java.awt.Color(0, 109, 167));
        año.setText("1911");
        add(año, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 40, 20));

        años.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        años.setForeground(new java.awt.Color(0, 109, 167));
        años.setText("Años: 111");
        add(años, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 150, 20));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image1;
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel año;
    private javax.swing.JLabel años;
    private javax.swing.JPanel body;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
