/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ps_Inventario;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import static ps_Inventario.Dashboard.content;
/**
 *
 * @author Antonio
 */
public class UpElementos extends javax.swing.JPanel {

    Connect conn;
    Connection reg;
    boolean edition;
    String origId;
    /**
     * Creates new form Principal
     */
    public UpElementos() {
        initComponents();
        conn = new Connect();
        reg = conn.getConnection();
        edition = false;
    }
    
    public UpElementos(String bid, String belemento, String bdate, String bcategory, String bdesc, String bstock, String bavai){
        initComponents();
        conn = new Connect();
        reg = conn.getConnection();
        edition = true;
        origId = bid;
        id.setText(bid);
        elemento.setText(belemento);
        date.setText(bdate);    
        category.setText(bcategory);  
        descr.setText(bdesc);
        stock.setText(bstock);
        available.setText(bavai);
        jLabel1.setText("Guardar");
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        button = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Text6 = new javax.swing.JLabel();
        elemento = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        Text7 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        Text9 = new javax.swing.JLabel();
        category = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        Text12 = new javax.swing.JLabel();
        descr = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        Text13 = new javax.swing.JLabel();
        stock = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        available = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        Text15 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 238, 238));
        setMinimumSize(new java.awt.Dimension(870, 430));
        setPreferredSize(new java.awt.Dimension(870, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("Cargar nuevo Articulos");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 10, 310));

        button.setBackground(new java.awt.Color(210, 110, 35));
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonMousePressed(evt);
            }
        });
        button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Subir");
        button.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, 30));

        add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 260, 50));

        Text3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text3.setText("Articulo ID");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        id.setBackground(new java.awt.Color(238, 238, 238));
        id.setForeground(new java.awt.Color(102, 102, 102));
        id.setText("Ingrese el ID del Elemento");
        id.setBorder(null);
        id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                idMousePressed(evt);
            }
        });
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 260, 30));

        jSeparator4.setBackground(new java.awt.Color(240, 240, 240));
        jSeparator4.setForeground(new java.awt.Color(248, 130, 41));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 260, 10));

        Text6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text6.setText("Título");
        add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        elemento.setBackground(new java.awt.Color(238, 238, 238));
        elemento.setForeground(new java.awt.Color(102, 102, 102));
        elemento.setText("Ingrese el Título");
        elemento.setBorder(null);
        elemento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                elementoMousePressed(evt);
            }
        });
        elemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elementoActionPerformed(evt);
            }
        });
        add(elemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 260, 30));

        jSeparator7.setBackground(new java.awt.Color(240, 240, 240));
        jSeparator7.setForeground(new java.awt.Color(248, 130, 41));
        jSeparator7.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 260, 10));

        Text7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text7.setText("Fecha de Publicación");
        add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        date.setBackground(new java.awt.Color(238, 238, 238));
        date.setForeground(new java.awt.Color(102, 102, 102));
        date.setText("Ingrese la Fecha de Publicación");
        date.setBorder(null);
        date.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dateMousePressed(evt);
            }
        });
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 260, 30));

        jSeparator8.setBackground(new java.awt.Color(240, 240, 240));
        jSeparator8.setForeground(new java.awt.Color(248, 130, 41));
        jSeparator8.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 260, 10));

        Text9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text9.setText("Categoría");
        add(Text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, -1));

        category.setBackground(new java.awt.Color(238, 238, 238));
        category.setForeground(new java.awt.Color(102, 102, 102));
        category.setText("Ingrese la Categoría del Elemento");
        category.setBorder(null);
        category.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                categoryMousePressed(evt);
            }
        });
        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });
        add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 260, 30));

        jSeparator10.setBackground(new java.awt.Color(240, 240, 240));
        jSeparator10.setForeground(new java.awt.Color(248, 130, 41));
        jSeparator10.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 260, 10));

        Text12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text12.setText("Descripción");
        add(Text12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, -1, -1));

        descr.setBackground(new java.awt.Color(238, 238, 238));
        descr.setForeground(new java.awt.Color(102, 102, 102));
        descr.setText("Ingrese la descripción del Elemento");
        descr.setBorder(null);
        descr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                descrMousePressed(evt);
            }
        });
        descr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descrActionPerformed(evt);
            }
        });
        add(descr, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 260, 30));

        jSeparator13.setBackground(new java.awt.Color(240, 240, 240));
        jSeparator13.setForeground(new java.awt.Color(248, 130, 41));
        jSeparator13.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 260, 10));

        Text13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text13.setText("Stock");
        add(Text13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        stock.setBackground(new java.awt.Color(238, 238, 238));
        stock.setForeground(new java.awt.Color(102, 102, 102));
        stock.setText("Cantidad Total");
        stock.setBorder(null);
        stock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                stockMousePressed(evt);
            }
        });
        stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockActionPerformed(evt);
            }
        });
        add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 80, 30));

        jSeparator14.setBackground(new java.awt.Color(240, 240, 240));
        jSeparator14.setForeground(new java.awt.Color(248, 130, 41));
        jSeparator14.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 80, 10));

        available.setBackground(new java.awt.Color(238, 238, 238));
        available.setForeground(new java.awt.Color(102, 102, 102));
        available.setText("Cantidad a prestar");
        available.setBorder(null);
        available.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                availableMousePressed(evt);
            }
        });
        available.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availableActionPerformed(evt);
            }
        });
        add(available, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 100, 30));

        jSeparator16.setBackground(new java.awt.Color(240, 240, 240));
        jSeparator16.setForeground(new java.awt.Color(248, 130, 41));
        jSeparator16.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 100, 10));

        Text15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text15.setText("Disponibles");
        add(Text15, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseEntered
        setColor(button);
    }//GEN-LAST:event_buttonMouseEntered

    private void buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseExited
        resetColor(button);
    }//GEN-LAST:event_buttonMouseExited

    private void idMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idMousePressed
       if(id.getText().equals("Ingrese el ID del Elemento"))
        id.setText("");
       if(elemento.getText().equals("") || elemento.getText() == null || elemento.getText().equals(" "))
        elemento.setText("Ingrese el Nombre");
       if(date.getText().equals("") || date.getText() == null || date.getText().equals(" "))
        date.setText("Ingrese la Fecha de Publicación");
       if(category.getText().equals("") || category.getText() == null || category.getText().equals(" "))
        descr.setText("Ingrese la descripción del Elemento");
       if(stock.getText().equals("") || stock.getText() == null || stock.getText().equals(" "))
        stock.setText("Cantidad Total");
       if(available.getText().equals("") || available.getText() == null || available.getText().equals(" "))
        available.setText("Cantidad a prestar");
    }//GEN-LAST:event_idMousePressed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void elementoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elementoMousePressed
        if(elemento.getText().equals("Ingrese el Título"))
        elemento.setText("");
       if(id.getText().equals("") || id.getText() == null || id.getText().equals(" "))
        id.setText("Ingrese el ID del Articulo");
       if(date.getText().equals("") || date.getText() == null || date.getText().equals(" "))
        date.setText("Ingrese la Fecha de Publicación");
       if(category.getText().equals("") || category.getText() == null || category.getText().equals(" "))
        category.setText("Ingrese la Categoría del Articulo");
       if(descr.getText().equals("") || descr.getText() == null || descr.getText().equals(" "))
        descr.setText("Ingrese la descripción del Elemento");
       if(stock.getText().equals("") || stock.getText() == null || stock.getText().equals(" "))
        stock.setText("Cantidad Total");
       if(available.getText().equals("") || available.getText() == null || available.getText().equals(" "))
        available.setText("Cantidad a prestar");
    }//GEN-LAST:event_elementoMousePressed

    private void elementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elementoActionPerformed

    private void dateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateMousePressed
        if(date.getText().equals("Ingrese la Fecha de Publicación"))
        date.setText("");
       if(id.getText().equals("") || id.getText() == null || id.getText().equals(" "))
        id.setText("Ingrese el ID del Elemento");
       if(elemento.getText().equals("") || elemento.getText() == null || elemento.getText().equals(" "))
        elemento.setText("Ingrese el Título");
       if(category.getText().equals("") || category.getText() == null || category.getText().equals(" "))
        category.setText("Ingrese la Categoría del Elemento");
       if(descr.getText().equals("") || descr.getText() == null || descr.getText().equals(" "))
        descr.setText("Ingrese la descripción del Elemento");
       if(stock.getText().equals("") || stock.getText() == null || stock.getText().equals(" "))
        stock.setText("Cantidad Total");
       if(available.getText().equals("") || available.getText() == null || available.getText().equals(" "))
        available.setText("Cantidad a prestar");
    }//GEN-LAST:event_dateMousePressed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void categoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryMousePressed
        if(category.getText().equals("Ingrese la Categoría del Elemento"))
        category.setText("");
       if(id.getText().equals("") || id.getText() == null || id.getText().equals(" "))
        id.setText("Ingrese el ID del Elemento");
       if(elemento.getText().equals("") || elemento.getText() == null || elemento.getText().equals(" "))
        elemento.setText("Ingrese el Título");
       if(date.getText().equals("") || date.getText() == null || date.getText().equals(" "))
        date.setText("Ingrese la Fecha de Publicación");
       if(descr.getText().equals("") || descr.getText() == null || descr.getText().equals(" "))
        descr.setText("Ingrese la descripción del Elemento");
       if(stock.getText().equals("") || stock.getText() == null || stock.getText().equals(" "))
        stock.setText("Cantidad Total");
       if(available.getText().equals("") || available.getText() == null || available.getText().equals(" "))
        available.setText("Cantidad a prestar");
    }//GEN-LAST:event_categoryMousePressed

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryActionPerformed

    private void descrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descrMousePressed
        if(descr.getText().equals("Ingrese la descripción del Elemento"))
        descr.setText("");
       if(id.getText().equals("") || id.getText() == null || id.getText().equals(" "))
        id.setText("Ingrese el ID del Elemento");
       if(elemento.getText().equals("") || elemento.getText() == null || elemento.getText().equals(" "))
        elemento.setText("Ingrese el Título");
       if(date.getText().equals("") || date.getText() == null || date.getText().equals(" "))
        date.setText("Ingrese la Fecha de Publicación");
       if(category.getText().equals("") || category.getText() == null || category.getText().equals(" "))
        category.setText("Ingrese la Categoría del Elemento");
       if(stock.getText().equals("") || stock.getText() == null || stock.getText().equals(" "))
        stock.setText("Cantidad Total");
       if(available.getText().equals("") || available.getText() == null || available.getText().equals(" "))
        available.setText("Cantidad a prestar");
    }//GEN-LAST:event_descrMousePressed

    private void descrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descrActionPerformed

    private void stockMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockMousePressed
        if(stock.getText().equals("Cantidad Total"))
        stock.setText("");
       if(id.getText().equals("") || id.getText() == null || id.getText().equals(" "))
        id.setText("Ingrese el ID del Elemento");
       if(elemento.getText().equals("") || elemento.getText() == null || elemento.getText().equals(" "))
        elemento.setText("Ingrese el Título");
       if(date.getText().equals("") || date.getText() == null || date.getText().equals(" "))
        date.setText("Ingrese la Fecha de Publicación");
       if(category.getText().equals("") || category.getText() == null || category.getText().equals(" "))
        category.setText("Ingrese la Categoría del Elemento");
       if(descr.getText().equals("") || descr.getText() == null || descr.getText().equals(" "))
        descr.setText("Ingrese la descripción del Elemento");
       if(available.getText().equals("") || available.getText() == null || available.getText().equals(" "))
        available.setText("Cantidad a prestar");
    }//GEN-LAST:event_stockMousePressed

    private void stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockActionPerformed

    private void availableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_availableMousePressed
        if(available.getText().equals("Cantidad a prestar"))
        available.setText("");
       if(id.getText().equals("") || id.getText() == null || id.getText().equals(" "))
        id.setText("Ingrese el ID del Elemento");
       if(elemento.getText().equals("") || elemento.getText() == null || elemento.getText().equals(" "))
        elemento.setText("Ingrese el Título");
       if(date.getText().equals("") || date.getText() == null || date.getText().equals(" "))
        date.setText("Ingrese la Fecha de Publicación");
       if(category.getText().equals("") || category.getText() == null || category.getText().equals(" "))
        category.setText("Ingrese la Categoría del Elemento");
       if(descr.getText().equals("") || descr.getText() == null || descr.getText().equals(" "))
        descr.setText("Ingrese la descripción del Elemento");
       if(stock.getText().equals("") || stock.getText() == null || stock.getText().equals(" "))
        stock.setText("Cantidad Total");
    }//GEN-LAST:event_availableMousePressed

    private void availableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availableActionPerformed

    // SUBIR
    private void buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMousePressed
        if(elemento.getText().equals("Ingrese el Título")
            || date.getText().equals("Ingrese la Fecha de Publicación") 
            || category.getText().equals("Ingrese la Categoría del Elemento")
            || descr.getText().equals("Ingrese la descripción del Elemento")|| stock.getText().equals("Cantidad Total")
            || available.getText().equals("Cantidad a prestar")){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            id.requestFocus();
        }
        else
        {
            String bid = id.getText();
            String belemento = elemento.getText();
            String bdate = date.getText();
           
            String bcategory = category.getText();
       
            String bdescr = descr.getText();
            String bstock = stock.getText();
            String bavailable = available.getText();
            
            int stc=0;
            int av=0;

            if(bid == null || "".equals(bid) || belemento == null || "".equals(belemento) || bdate == null || "".equals(bdate) 
                    || bcategory == null || "".equals(bcategory) 
      
                    || bdescr == null || "".equals(bdescr) || bstock == null || "".equals(bstock) 
                    || bavailable == null || "".equals(bavailable)){
                javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                id.requestFocus();
            }
            else{ 
                try{
                    
                    stc = Integer.parseInt(bstock);
                    av = Integer.parseInt(bavailable);

                    try {
                        if(edition)
                            EditArticulo(bid, belemento, bdate,  bcategory, bdescr, stc, av);
                        else
                            InsertArticulo(belemento, bdate,  bcategory, bdescr, stc, av);

                        id.setText("");
                        elemento.setText("");
                        date.setText("");
                       
                        category.setText("");
                        
                        descr.setText("");
                        stock.setText("");
                        available.setText("");
                        

                        if(edition){
                            Articulos p1 = new Articulos();
                            p1.setSize(850, 430);
                            p1.setLocation(0, 0);

                            content.removeAll();
                            content.add(p1, BorderLayout.CENTER);
                            content.revalidate();
                            content.repaint();
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(UpUsers.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }catch(NumberFormatException ex){
                    javax.swing.JOptionPane.showMessageDialog(this, "Las páginas, el Stock y el Disponible, deben ser números enteros. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    id.requestFocus();
                }

            }
        }
    }//GEN-LAST:event_buttonMousePressed

    void setColor(JPanel panel){
        panel.setBackground(new Color(248, 130, 41));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(210, 110, 35));
    }
    
    public void InsertArticulo(String elem, String fech, String cate, String desc, int stck, int avai) throws SQLException{
        Statement stm = reg.createStatement();
        
        stm.executeUpdate("INSERT INTO `articulos` (`id`, `elemento`, `date`, `category`, `description`, `stock`, `available`) VALUES ((SELECT max(id)+1 FROM articulos), '"+elem+"', '"+ fech +"', '"+cate+"', '"+desc+"', '"+stck+"', '"+avai+"')");
        javax.swing.JOptionPane.showMessageDialog(this, "¡Elemento registrado correctamente! \n", "HECHO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
    }
    
    public void EditArticulo(String id, String elem, String fech, String cate, String desc, int stck, int avai) throws SQLException{
        Statement stm = reg.createStatement();
        
        stm.executeUpdate("UPDATE `articulos` SET `id` = '"+id+"', `elemento` = '"+elem+"', `date` = '"+fech+"', `category` = '"+cate+"', `description` = '"+desc+"', `stock` = '"+stck+"', `available` = '"+avai+"' WHERE `id` = '"+ origId +"';");
        javax.swing.JOptionPane.showMessageDialog(this, "¡Elemento editado correctamente! \n", "HECHO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text12;
    private javax.swing.JLabel Text13;
    private javax.swing.JLabel Text15;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Text9;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField available;
    private javax.swing.JPanel body;
    private javax.swing.JPanel button;
    private javax.swing.JTextField category;
    private javax.swing.JTextField date;
    private javax.swing.JTextField descr;
    private javax.swing.JTextField elemento;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField stock;
    // End of variables declaration//GEN-END:variables
}
